<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Schema\game-data-schema.json">
      <LogicalName>MapEditor.GameData.game-data-schema.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
